---

#This task should back up the configuration of all devices defined in cisco group.
#The backup parameter automatically creates a directory called backup within the playbook root and saves a time-stamped backup of the running configuration.

- name: BACKUP ROUTER CONFIGURATIONS
  hosts: cisco
  connection: network_cli
  gather_facts: no


#this will automatically have created a backup folder
  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output

    - name: RENAME BACKUP
      copy:
        src: "{{config_output.backup_path}}"
#using the ansible level variable for the inventory hostname
        dest: "./backup/{{inventory_hostname}}.config"

#if trying to restore from the file above, errors would come up as a result of "Building configuration ..." when peforming a show run
#so the answer to this is: remove non config lines:

    - name: REMOVE NON CONFIG LINES
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        line: "Building configuration..."
#line needs to be an exact match
        state: absent

#sometimes regex have to be used instead such as in the example below:
    - name: REMOVE NON CONFIG LINES - REGEXP
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        regexp: 'Current configuration.*'
        state: absent

