---
- name: GENERATE OS REPORT FROM ROUTERS
  hosts: cisco
  connection: network_cli
  gather_facts: no

#In this lab you will learn how to use the template module to pass collected
 data from devices to a Jinja2 template. The template module then renders th
e output as a markdown file.

  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:

#### formating start:   Rather than using debug or verbose mode to display t
he output on the screen, go ahead and add a new task using the template modu
le as follows:

    - name: ENSURE REPORTS FOLDER
      run_once: true
      file:
        name: reports
        state: directory

    - name: RENDER FACTS AS A REPORT
      template:
        src: os_report.j2
        dest: reports/{{ inventory_hostname }}.md

#### formating end

##consolidating into a single file
    - name: CONSOLIDATE THE IOS DATA
      assemble:
        src: reports/
        dest: network_os_report.md
      delegate_to: localhost
      run_once: yes
